### PR TITLE
Added 5 More Elon's Favorite Emoji's to Algorithm.ts + Grammatical Errors fixed on Index Page 

### PR DESCRIPTION
**Pull request by Arthavruksha**
- Added Emojis - 

🤖 Robot Face: used in tweets about robotics or AI.
🌞 Sun: used in tweets about solar power or renewable energy.
🌍 Globe Showing Americas: used to indicate global impact or presence, particularly in North or South America.
🧢 Billed Cap: used to indicate support for a political or social movement, particularly related to the United States.
🥳 Partying Face: used to indicate celebration or excitement.

- Grammatical Error Fix - 

From - "the open source Twitter algorithm" to "Twitter's Open Source Algorithm"

### CODE REVIEW

**Comment by Arthavruksha** [comment]
Let me know what do you think about this @coryetzkorn

**Comment by user670** [comment]
You've already been rejected once for the same addition.

**Comment by Arthavruksha** [comment]
> You've already been rejected once for the same addition.

Nope , I removed that request myself because it had errors in it and opened this one which was correct

**Comment by coryetzkorn** [comment]
Thanks for your contribution to open source!

**Comment by Arthavruksha** [comment]
This was my first kinda actual contribution to open source , enjoyed it !

**Pull request merged**
